[package]
name = "rustycube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.2.4"
env_logger = "0.10.0"
libmem = "4.1.0"
log = "0.4.19"
